# -*- coding: utf-8 -*-
"""forca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gslWL6QefvSKdMm-XGSBLI3zf_s-8UqO
"""

def criarBase(nome):

    palavras = "banana acerola caju laranja verde vermelho azul rosa carro moto barco"

    base = open(nome, 'w')

    base.write(palavras)

    base.close()

def listarPalavras(nome):

    base = open(nome, 'r')

    palavras = base.read().split()

    base.close()

    return palavras

def criarJogo():

    nome = "base.txt"
    criarBase(nome)

    import random

    palavra = random.choice(listarPalavras(nome))

    montagem = []

    for n in range(len(palavra)): montagem.append("-")

    jogo = dict(palavra = palavra, montagem = montagem, acertos = [], erros = [], quantPalpites = 0, terminou = False, ganhou = False)

    return jogo
    
def criarJogador():

    nome = str(input("Insira seu nome: "))
    email = str(input("Insira seu email: "))

    jogador = dict(nome = nome, email = email)

    print("")

    return jogador

def validarEntrada(letra, acertos):

    if(len(letra) > 1): 
        
        print("Insira apenas uma letra!")

        return False

    elif(not letra.isalpha()):
        
        print("Insira uma letra do alfabeto!")

        return False

    elif(letra in acertos):

        print("Insira uma letra diferente!")

        return False

    else: return True

def fazerJogada(jogo):

    if(len(jogo['erros']) <= 5):
        
        letra = str(input("\nInsira uma letra: ").lower())

        if(not validarEntrada(letra, jogo['acertos'])): 
            
            fazerJogada(jogo)

        elif(letra not in jogo['palavra']):

            jogo['erros'].append(letra)

            print("A letra inserida não ocorre na palavra.\n")
            
        else: 

            jogo['acertos'].append(letra)

            print("Você acertou uma letra!\n")

            for n in range(len(jogo['palavra'])):

                if(jogo['palavra'][n] == letra): jogo['montagem'][n] = letra

            if(jogo['palavra'] == "".join(jogo['montagem'])): 

                print("Parabéns, você acertou todas as letras da palavra e terminou o jogo!\n")

                jogo['terminou'] = jogo['ganhou'] = True

    else: 
        
        print("Você já usou todas sua tentativas.\n")

        jogo['terminou'] = True

def fazerPalpite(jogo):

    if(jogo['quantPalpites'] <= 3):

        palpite = str(input("\nInsira seu palpite: ").lower())

        if(palpite == jogo['palavra']):

            print("Parabéns, você acertou a palavra e terminou o jogo!\n")

            jogo['terminou'] = jogo['ganhou'] = True

        else:

            jogo['quantPalpites'] += 1

            print("Palpite incorreto.")

    else: 
        
        print("Você já usou todos seus palpites.\n")

        jogo['terminou'] = True

def imprimirResumo(jogo):

    print("Palavra: ", end = "")

    for letra in jogo['montagem']: 

        if(letra == '-'): print("_ ", end = "")
        else: print("%s " % letra, end = "")

    print("\n\nLetras acertadas: ", jogo['acertos'])
    print("Letras erradas: ", jogo['erros'])
    print("Tentativas de letra disponíveis: ", 5 - len(jogo['erros']))
    print("Palpites disponíveis: ", 3 - jogo['quantPalpites'])

def salvarJogo(jogo, jogador):

    arquivo = open("jogo.txt", 'a')

    arquivo.write(jogador['nome'] + "\n")
    arquivo.write(jogador['email'] + "\n")
    arquivo.write(jogo['palavra'] + "\n")
    arquivo.write("Ganhou: " + str(jogo['ganhou']) + "\n\n")

    arquivo.close()

def main():

    jogo = criarJogo()

    print("Bem-vindo ao jogo de forca em Python!\n")

    jogador = criarJogador()

    imprimirResumo(jogo)
    fazerJogada(jogo)
    imprimirResumo(jogo)

    while(not jogo['terminou']):

        res = str(input("\nGostaria de tentar mais uma letra ou tentar um palpite da palavra? (L/P): ").upper())

        if(res == 'L'): 
            
            fazerJogada(jogo)
            imprimirResumo(jogo)

        elif(res == 'P'): fazerPalpite(jogo)
        else: print("Opção inválida!")

    salvarJogo(jogo, jogador)

main()